title: Reverse Archaeology Content
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/reverse-archaeology-content"
url: "https://uofo.github.io"

# Build settings
markdown: kramdown

collections:
  artifacts:
    output: true
  bios:
    output: true
  funders:
    output: true
  partners:
    output: true
  slideshowimages:
    output: true

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Request-Method: "GET"

prose:
  metadata:
    _artifacts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "headline"
        field:
          element: "text"
          label: "Headline"
      - name: "image_url"
        field:
          element: "text"
          label: "Image URL"
      - name: "image_caption"
        field:
          element: "text"
          label: "Image Caption"
      - name: "name"
        field:
          element: "text"
          label: "Name (interviewee or story subject)"
      - name: "location_latitude"
        field:
          element: "number"
          label: "Location Latitude"
      - name: "location_longitude"
        field:
          element: "number"
          label: "Location Longitude"
      - name: "learn_more_url"
        field:
          element: "text"
          label: "Learn More URL"
      - name: "themes"
        field:
          element: "multiselect"
          label: "Themes"
          alterable: true
          options:
            - name: "The History of US cities you can learn in Orange, NJ"
              value: "history-us-cities"
            - name: "Orange is a Crossroads"
              value: "crossroads"
            - name: "The Corner of Good Hope"
              value: "corner-good-hope"
            - name: "Lifecycle"
              value: "lifecycle"
            - name: "Industry and Infrastructure"
              value: "industry-and-infrastructure"
            - name: "Nostalgia and Curiosity"
              value: "nostalgia"
      - name: "subthemes"
        field:
          element: "text"
          label: "Subthemes"
    _bios:
      - name: "name"
        field:
          element: "text"
          label: "Name"
      - name: "title_affiliation"
        field:
          element: "text"
          label: "Title / Affiliation"
      - name: "image_url"
        field:
          element: "text"
          label: "Image URL"
    _funders:
      - name: "name"
        field:
          element: "text"
          label: "Name"
      - name: "image_url"
        field:
          element: "text"
          label: "Image URL"
    _partners:
      - name: "name"
        field:
          element: "text"
          label: "Name"
      - name: "image_url"
        field:
          element: "text"
          label: "Image URL"
      - name: "website"
        field:
          element: "text"
          label: "Website"
    _slideshowimages:
      - name: "caption"
        field:
          element: "text"
          label: "Caption"
      - name: "image_url"
        field:
          element: "text"
          label: "Image URL"
      - name: "page"
        field:
          element: "select"
          label: "Page"
          options:
            - name: "About"
              value: "about"
            - name: "Chasm"
              value: "chasm"
            - name: "Prism"
              value: "prism"
