title: Reverse Archaeology Content
baseurl: "/jekyll-spa-content"
url: "https://uofo.github.io"

# Build settings
markdown: kramdown

collections:
  artifacts:
    output: true

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Request-Method: "GET"

prose:
  metadata:
    _artifacts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "image_url"
        field:
          element: "text"
          label: "Image URL"
      - name: "video_url"
        field:
          element: "text"
          label: "Video URL"
